#!/usr/bin/env bash
# Using the awk command to print 
log_file="apache-access.log"
if [ -e "$log_file" ]; then
	awk '{print $1, $9}' "$log_file"
else
	echo "The log file $log_file does not exist."
fi
